name: Deploy to Vercel

# mainブランチにpushをトリガーにする
on:
  push:
    branches:
      - main 

# ジョブを定義
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4   # リポジトリのコードをクローンする

      - uses: actions/setup-node@v4 # node.jsをセットアップする
        with:
          node-version: '22'        # nodeのバージョン22を指定

      - run: npm ci

      - run: npm run test

      - run: npm install -g vercel@latest

      - run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
